### ISSUE TITLE
[Errno 2] No such file or directory: '/content/output_dir/esm2_t48/A0A8M9Q0I3_0.pt'

### ISSUE THREAD

**Issue by Hamid-R-Moradi** [BioinfoMachineLearning/TransFew#1]
Hi, I hope you are doing well. 
I want to use TransFew to predict the functionality of few proteins in google colab. However I can't get pass the provided example and constantly run into this error:
[Errno 2] No such file or directory: '/content/output/esm2_t48/A0A8M9Q0I3_0.pt'

I have installed the following packages:
`!pip install --pre biopython obonet biopandas torch-geometric fair-esm torch`

and cloned the project:
```
!git clone https://github.com/BioinfoMachineLearning/TransFew.git
!cp -r /content/TransFew/* /content/
!rm -r TransFew/ 
```
and used this code to predict the functionalities of the provided test fasta  file proteins:
`!python /content/predict.py  --data-path /content --fasta-path /content/output_dir/test_fasta.fasta --ontology mf --working-dir /content/output_dir --output result.tsv`

but it outputs this error:
"""
python -u external/extract.py esm2_t48_15B_UR50D /content/output/temp.fasta /content/output/esm2_t48 --repr_layers 48 --include mean per_tok --toks_per_batch 100
Killed
Traceback (most recent call last):
  File "/content/predict.py", line 171, in <module>
    proteins = generate_embeddings(in_fasta=fasta_path, wd=wd)
  File "/content/predict.py", line 107, in generate_embeddings
    merge_pts(keys, fasta_path, wd)
  File "/content/predict.py", line 48, in merge_pts
    tmp.append(torch.load(os_path))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/content/output_dir/esm2_t48/A0A8M9Q0I3_0.pt'
""""
could you please provide some ideas on how to overcome this problem?

**Comment by dannyoo** [comment]
do you have a gpu? cause it looks like it's getting killed from an OOM issue
